export { api, ApiError } from './client'
export { authApi } from './auth'
export { projectsApi } from './projects'
export { notesApi } from './notes'
export { tasksApi } from './tasks'
export { filesApi } from './files'
export { searchApi } from './search'
export { tagsApi } from './tags'
export { aiApi } from './ai'
export type * from './dto'
